chore: improve GitHub integration, add CI config
InfluxCommunity/influxdb3-python pull request #78
Opened 2024-03-14 08:15 UTC by bednar

This PR introduce support for CI integration (next PRs will enable code style checks) add templates for GitHub issues, ...

2024-03-15 08:58 UTC, karel-rehor requested changes
@bednar Can you double check line 50 of setup.py?  While python 3.7 was removed from classifiers, it is still included there as part of the logic of `python_requires`.

Otherwise, looks great.

2024-03-15 08:58 UTC, karel-rehor commented on setup.py
I see Python 3.7 has been removed from classifiers.  However on line 50 `python_requires='>=3.7'`, so 3.7 will still be supported or should line 50 be `python_requires='>=3.8'`

2024-03-15 09:17 UTC, bednar commented on setup.py
Fixed, I've add `python_requires='>=3.8`

2024-03-18 09:11 UTC, karel-rehor approved these changes
Looks good.

2024-03-18 11:57 UTC, merged